---
- name: download terraform...
  get_url: >
    url={{terraform_url}}
    dest=/tmp/{{terraform_zip}}
    owner=root
    group=root
    mode=644

- name: create /opt/terraform_version
  file: >
    owner=root
    group=root
    mode=755
    path={{terraform_install_dir}}/{{terraform_name}}
    state=directory
  
- name: unarchive terraform...
  unarchive: >
    copy=no
    src=/tmp/{{terraform_zip}}
    dest={{terraform_install_dir}}/{{terraform_name}}

- name: link /opt/terraform
  file: >
    src={{terraform_install_dir}}/{{terraform_name}}
    dest={{terraform_install_dir}}/terraform
    state=link
    owner=root
    group=root

- name: include terraform-* in the default path...
  copy: >
    src=etc/profile.d/terraform.sh
    dest=/etc/profile.d/terraform.sh
    mode=644
    owner=root
    group=root